#ifndef __MFGFOUNDATIONVERSION_H__
#define __MFGFOUNDATIONVERSION_H__

#define MFG_FOUNDATION_VERSION_MAJOR 6
#define MFG_FOUNDATION_VERSION_MINOR 0
#define MFG_FOUNDATION_VERSION_PATCH 1
#define MFG_FOUNDATION_VERSION_SUFFIX
#define MFG_FOUNDATION_VERSION_RELEASE 3
#define MFG_FOUNDATION_VERSION_NAME "mfgfoundation"

#define MFG_FOUNDATION_VERSION_NUM    ((MFG_FOUNDATION_VERSION_MAJOR << 16) | (MFG_FOUNDATION_VERSION_MINOR << 8) | MFG_FOUNDATION_VERSION_PATCH)

#define STR_EXPAND(tok) #tok
#define STR(tok) STR_EXPAND(tok)

#define MFG_FOUNDATION_VERSION STR(MFG_FOUNDATION_VERSION_MAJOR) "." STR(MFG_FOUNDATION_VERSION_MINOR) "." STR(MFG_FOUNDATION_VERSION_PATCH) " " STR(MFG_FOUNDATION_VERSION_SUFFIX)
#define MFG_FOUNDATION_SOVERSION STR(MFG_FOUNDATION_VERSION_MAJOR) "." STR(MFG_FOUNDATION_VERSION_MINOR)

#endif /* __MFGFOUNDATIONVERSION_H__ */
